on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

env:
  # `BASE_URL` determines the website is served from, including CSS & JS assets
  # You may need to change this to `BASE_URL: ''`
  BASE_URL: /${{ github.event.repository.name }}

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm libclang-dev
      - name: Install rust dependencies
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Install dev dependencies
        run: |
          uv sync --group dev
      - name: Build documentation
        run: |
          cd docs && uv run jupyter book build --html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docs/_build/html"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
